// Writes src/data/snapshot.js from the live API: the real content the public
// site renders instantly while the API is loading, or if it is unreachable.
// Refresh after large Admin edits: `npm run snapshot` (API must be running).
import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'

const root = new URL('..', import.meta.url)

function apiBase() {
  if (process.env.VITE_API_URL) return process.env.VITE_API_URL
  try {
    const env = readFileSync(new URL('.env', root), 'utf8')
    const match = env.match(/^VITE_API_URL=(.+)$/m)
    if (match) return match[1].trim()
  } catch {
    // no .env — use the default below
  }
  return 'http://localhost:5000/api'
}

const DROP = new Set(['__v', 'createdAt', 'updatedAt', 'status'])

function clean(value) {
  if (Array.isArray(value)) return value.map(clean)
  if (value && typeof value === 'object') {
    return Object.fromEntries(
      Object.entries(value)
        .filter(([key]) => !DROP.has(key))
        .map(([key, v]) => [key, clean(v)])
    )
  }
  return value
}

const base = apiBase().replace(/\/$/, '')
const res = await fetch(`${base}/site`)
if (!res.ok) throw new Error(`GET ${base}/site failed (${res.status})`)
const site = await res.json()

// The resume link only works when the API is up, so it is never snapshotted.
const snapshot = clean({
  profile: site.profile,
  content: site.content,
  projects: site.projects,
  skills: site.skills,
  experience: site.experience,
})

const file = fileURLToPath(new URL('src/data/snapshot.js', root))
writeFileSync(
  file,
  `// Generated by \`npm run snapshot\` from ${base}/site — do not edit by hand.\n` +
    `// Real content shown while the API loads or if it is unreachable.\n` +
    `export const snapshot = ${JSON.stringify(snapshot, null, 2)}\n`
)
console.log(
  `Snapshot written: ${snapshot.projects.length} projects, ${snapshot.skills.length} skills, ${snapshot.experience.length} experience`
)
